### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by aficionadoai** [yingkaisha/keras-unet-collection#1]
Can you provide an example how to use backbones? Is there a list of backbones supported?

**Comment by aficionadoai** [comment]
One example that my be helpful in regards to unet3+ is model checkpoint for deep supervision.

**Comment by yingkaisha** [comment]
I would build a model and assign stored weights through `model.set_weights()`

A Jupyter notebook is available for UNET 3+ and deep-supervision.

https://github.com/yingkaisha/keras-unet-collection/blob/main/examples/segmentation_unet-three-plus_oxford-iiit.ipynb

**Comment by aficionadoai** [comment]
@yingkaisha Thank you!

**Comment by aficionadoai** [comment]
"I would build a model and assign stored weights through model.set_weights()"

Is the use case the same as model.save_weights().   Should I place model.set_weights after model.fit of after compile?

**Comment by yingkaisha** [comment]
Should be after compiling.
