### ISSUE TITLE
UNET with transformer

### ISSUE THREAD

**Issue by atgc1984** [yingkaisha/keras-unet-collection#12]
您好，请问是否有计划添加基于transformer的UNET架构？如TransUNET或Swin-UNET（这个貌似还没开源）等。谢谢。

**Comment by yingkaisha** [comment]
我去看一下。TransUNET会在近期更新。

**Comment by yingkaisha** [comment]
TransUNET 更新了。可以在`pip install keras-unet-collection==0.1.0`后运行。

**Comment by yingkaisha** [comment]
@aficionadoai 

Updated TransUNET in the latest version. Somewhat experimental.

**Comment by atgc1984** [comment]
Thank you for the update! Will try it with my own project data.
