### ISSUE TITLE
After update, error in import module

### ISSUE THREAD

**Issue by arthurmteodoro** [yingkaisha/keras-unet-collection#14]
After update to 0.1.0, a Google Colab show the following error:

ModuleNotFoundError: No module named 'keras_unet_collection'.

The version of TensorFlow and Keras installed is 2.5.0.

**Comment by yingkaisha** [comment]
Sorry. I will work on this error soon.

**Comment by yingkaisha** [comment]
`pip install keras_unet_collection -U` should fix it.

**Comment by atgc1984** [comment]
> 
> 
> `pip install keras_unet_collection -U` should fix it.

Seems not working. Any suggestion?

**Comment by yingkaisha** [comment]
@atgc1984 Try `pip install keras-unet-collection==0.1.2`. I switched to the static config file and had a packaging issue.

**Comment by atgc1984** [comment]
> 
> 
> @atgc1984 Try `pip install keras-unet-collection==0.1.2`. I switched to the static config file and had a packaging issue.

Same error. I just removed the package and installed 0.1.2. Not sure if it is just my issue. @arthurmteodoro Arthur could you please try 0.1.2?

**Comment by yingkaisha** [comment]
@atgc1984  Sorry it's `pip install keras-unet-collection==0.1.3` I've deleted incorrect versions from the pipy sever.

**Comment by yingkaisha** [comment]
@atgc1984 Now `pip install keras-unet-collection==0.1.5` should work.

**Comment by yingkaisha** [comment]
@arthurmteodoro `pip install keras-unet-collection==0.1.5` seems solved on my side.

**Comment by atgc1984** [comment]
0.1.5 works! Thank you.
