### ISSUE TITLE
"freeze_backbone" as RHS for both "freeze_backbone" and "freeze_batch_norm" arguments

### ISSUE THREAD

**Issue by ironhide23586** [yingkaisha/keras-unet-collection#16]
The same value of freeze_backbone is being erroneously fed in to both these arguments; check it out at the permalink below-
https://github.com/yingkaisha/keras-unet-collection/blob/6ee55b172637756e1bbe8756ec81b02c6bebed02/keras_unet_collection/_model_transunet_2d.py#L430

Request a quick fix :) 

Cheers! ψ(｀∇´)ψ

**Comment by yingkaisha** [comment]
Hi I've fixed the issue; it is available in `pip install keras-unet-collection==0.1.7`.
