### ISSUE TITLE
Transunet for different image size (256x256)

### ISSUE THREAD

**Issue by mohameddhaifbelja** [yingkaisha/keras-unet-collection#17]
I tried to run the Transunet model for image segmentation on 256x256 images. This is the configuration I have used:
`    model = models.transunet_2d((256, 256, 3), filter_num=[64, 128, 256, 512], n_labels=7,
                                stack_num_down=2, stack_num_up=2,
                                proj_dim=768, num_mlp=3072, num_heads=12, num_transformer=12,
                                activation='ReLU', mlp_activation='GELU', output_activation='Softmax', 
                                batch_norm=True, pool=True, unpool='bilinear', name='transunet')`
However the following error appears:
`in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [16,4096,768] vs. [1024,768]
         [[node gradient_tape/transunet_model/vi_t_embedding/add/BroadcastGradientArgs (defined at transunet_test.py:18) ]] [Op:__inference_train_function_18605]`

I have tried to change the size of filters, but it produces the same "incompatible shapes" error but with different values and it always a factor of 4.  Another solution I tried is to work with a 512x512 but again the same problem.

**Comment by yingkaisha** [comment]
I will look into it today.

**Comment by yingkaisha** [comment]
I can reproduce this problem. Need more time to fix it. 

I will let you know the progress. Thank you.

**Comment by yingkaisha** [comment]
I've proposed a bug fix. It is available through `pip install keras-unet-collection==0.1.8`.

TransUNETs are large, I'm not able to do intensive tests. Let me know if the issue is solved.

Thank you.
