### ISSUE TITLE
Model saving issue for TransUNET

### ISSUE THREAD

**Issue by atgc1984** [yingkaisha/keras-unet-collection#18]
Hello, I got following error messages when training with TransUNET (with checkpoint saving callback):

_WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... Layer ViT_patch_gen has arguments in `__init__` and therefore must override `get_config`.
NotImplementedError: Layer ViT_patch_gen has arguments in `__init__` and therefore must override `get_config`._

Looks like Keras failed to save the model since it can't load it:
[https://stackoverflow.com/questions/58678836/notimplementederror-layers-with-arguments-in-init-must-override-get-conf](url)

Also at the beginning of 2nd epoch the training loop would break with:
_W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated._
I wrote my own data generator to load image tiles and it works fine with your UNET3+ or attUNET.
I tried a smaller batch size but it's not working, somehow not sure if this is related to the model source code. 

Please let me know if you need more details.

Many thanks.

**Comment by atgc1984** [comment]
Just an update:
The generator works ok after I turned off the model checkpoint callback.

**Comment by yingkaisha** [comment]
Yes. It is because TransUNET contains python objects that are not part of the `tf.keras`.

A workaround, for now, is to (1) configure the same TransUNET, and (2) load weights.

e.g.

```python
def dummy_loader(model_path):
    print('Import model:\n{}'.format(model_path))
    backbone = keras.models.load_model(model_path, compile=False)
    W = backbone.get_weights()
    return W

weights = dummy_loader(model_old_path)
model_new = models.transunet_2d(...)
model_new.set_weights(weights)
```

I will add some guidance and util functions for user convenience.

**Comment by yingkaisha** [comment]
Let me know if I identified correctly. I'm in the Pacific time so there might be a delay in response.

**Comment by atgc1984** [comment]
Thank you for the response. 
Do you mean to save the weight rather than the whole model?

**Comment by yingkaisha** [comment]
@atgc1984 Save the whole model and obtain its weights within a function scope.

**Comment by yingkaisha** [comment]
I've added notes in the user guide; the `dummy_loader()` is added to the utils.

Closing.
