### ISSUE TITLE
error on my dataset for unet3+

### ISSUE THREAD

**Issue by rosemolthomas30** [yingkaisha/keras-unet-collection#19]
I am a beginner. Help me solve the error I got for Unet 3+.

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-18-16e17bf71a5e> in <module>()
     14         temp_out = unet3plus.predict([valid_input])
     15         y_pred = temp_out[-1]
---> 16         record = np.mean(hybrid_loss(valid_target, y_pred))
     17         print('\tInitial loss = {}'.format(record))
     18 

9 frames
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Incompatible shapes: [87736320] vs. [1032192] [Op:Mul]

**Comment by yingkaisha** [comment]
It looks like a shape mismatch error, and may not be TensorFlow related. 

I'd recommend checking your training and validation data.
