### ISSUE TITLE
ValueError: Dimensions must be equal

### ISSUE THREAD

**Issue by aficionadoai** [yingkaisha/keras-unet-collection#2]
I get this error when I try to run the unet3plus with 512,512,3 as the input. 

`ValueError: Dimensions must be equal, but are 512 and 64 for '{{node binary_crossentropy_2/mul}} = Mul[T=DT_FLOAT](replicated_input_2, binary_crossentropy_2/Log)' with input shapes: [8,512,512,1], [8,64,64,1].`

**Comment by yingkaisha** [comment]
Hello, could you provide a single batch of data and your code snippets?

**Comment by aficionadoai** [comment]
I used your example code for the unet3+ 

`unet3plus = models.unet_3plus_2d((None, None, 3), n_labels=1, filter_num_down=[64, 128, 256, 512], 
                                  filter_num_skip='auto', filter_num_aggregate='auto', 
                                  stack_num_down=2, stack_num_up=1, activation='ReLU', output_activation='Sigmoid',
                                  batch_norm=False, pool=True, unpool=False, deep_supervision=True, name='unet3plus')`

My inputs size is 512,512,3

Also do I add `backbone = ` to use different backbones?

**Comment by yingkaisha** [comment]
I will put a hotfix for this issue soon.

**Comment by yingkaisha** [comment]
Do an upgrade to 0.0.8 and see if it works `pip install keras-unet-collection==0.0.8`

**Comment by yingkaisha** [comment]
The term "backbone" is somewhat confusing. So the backbone module of this package creates backbones with unet-like configurations. That said, using unet layers as feature extractors; not using ImageNet feature extractors to build unet.

Building Unet with other pre-trained models, e.g., VGG16, is currently not supported. But I might add several implementations in a one-month time frame.

**Comment by aficionadoai** [comment]
Thank you. So far it works. I'm testing it out on Kaggle's HuBMap competition. I'll let you know how it goes.
