### ISSUE TITLE
saving model error

### ISSUE THREAD

**Issue by LiyingChan** [yingkaisha/keras-unet-collection#23]
For models.swin_unet_2d:
ValueError: '_linear_trans1/' is not a valid scope name.
(It seems the name cannot contain '\_')

detailed information:
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at0x7f5480505eb8>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at0x7f5480417128>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at0x7f54803d8b38>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.convolutional.Conv2D object at0x7f548037ebe0>, because it is not built.
Traceback (most recent call last):
  File "unet_plus_binary.py", line 368, in <module>
    callbacks=snapshot.get_callbacks())
  File "lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1957, in fit_generator
    initial_epoch=initial_epoch)
  File "lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1229, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
...
  File "lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4275, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)

**Comment by yingkaisha** [comment]
Try `pip install keras-unet-collection==0.1.10`, let me know if it works.
