### ISSUE TITLE
configuration for more deep model

### ISSUE THREAD

**Issue by MiladGhorbaniG** [yingkaisha/keras-unet-collection#25]
Hi @yingkaisha , 
I am testing the models with a more complex problem. So I tried to increase depth of swin unet model with the following code: 
`model = swin_unet_2d(input_shape, filter_num_begin=64, n_labels=2, depth=8, stack_num_down=4, stack_num_up=4, 
					patch_size=(2, 2), num_heads=[4, 8, 8, 8,8, 8, 8,16], window_size=[4, 2, 2, 2,2, 2, 2,2], 
                                        num_mlp=512, utput_activation='Softmax', shift_window=True, name='swin_unet')`
The following error occurred. 

 

> ValueError: Dimensions must be equal, but are 4 and 1 for '{{node swin_transformer_block_28/window_attention_28/matmul_1}} = BatchMatMulV2[T=DT_FLOAT, adj_x=false, adj_y=false](swin_transformer_block_28/window_attention_28/dropout_84/Identity, swin_transformer_block_28/window_attention_28/strided_slice_2)' with input shapes: [?,16,4,4], [?,16,1,512].

What is wrong with my configuration?

**Comment by yingkaisha** [comment]
Thank you for the feedback. I will look into this issue in the coming days.

**Comment by MiladGhorbaniG** [comment]
It is greatly appreciated.

**Comment by yingkaisha** [comment]
The error looks like tensor size runs out. What is your `input_size`?  

Here `depth=8` means 8 times downsampling, each would half the input tensor. So your input size must be larger than 512-by-512.

**Comment by yingkaisha** [comment]
Also, note that your configuration has two billion weights. A giant model like this would be very hard to train.
