### ISSUE TITLE
how to visualize layers

### ISSUE THREAD

**Issue by rezadarooei** [yingkaisha/keras-unet-collection#31]
Thanks for your awesome library, it is absolutely a time saver. I have a question I want to visualize layers in the networks (feature maps)? Do you have any plan to develop this feature?

**Comment by yingkaisha** [comment]
Layer visualization is model-dependent, and it is hard to implement in a user-friendly way. 

The general idea is:

(1) Exploring all the hidden layers using `model.summary()`

(2) Configuring a new model using the `get_layer()` method (either by names or the indices of layers). Visualize the prediction of this new model

```python
from tensorflow import keras
from keras.models import Model

# model = unet(...) # define and train your model
# model.summary() # explore your model layers

model_visualize = Model(inputs=[model.input,], outputs=[model.get_layer('layer_name').output,])
# using a list of "outputs=[layer1, layer2, layer3]" to visualize multiple layers

list_of_features = model_visualize.predict([single_sample,])
```

**Comment by yingkaisha** [comment]
I will close your previous issue if it has been solved.

**Comment by rezadarooei** [comment]
Thanks a lot for explanation. that's ok I got my last question. thanks
