### ISSUE TITLE
how to add recurrent iterations in different models?

### ISSUE THREAD

**Issue by rezadarooei** [yingkaisha/keras-unet-collection#32]
Hi, Thanks again for your nice library and sorry I'm sorry about asking many questions. I have a question is it possible to add recurrent iteration to the different models? for example, I want to add recurrent iterations to the decoder part of trans U-net or to the attention u-net to improve results. how it is possible?
Thanks again.

**Comment by yingkaisha** [comment]
Yes, it is possible to add recurrent iterations into CNN, including the U-net. This idea is known as "RCNN". This repository has an R2U-Net implementation that you can look at. For more advanced hybrids as mentioned in your question (recurrent + attention/trans u-net), I don't have good thoughts now. If you can find relevant publications, I will give them a try.

**Comment by rezadarooei** [comment]
there are R2aunet you can visit this paper and this implementation in PyTorch:
https://www.hindawi.com/journals/scn/2021/6625688/
https://github.com/LeeJunHyun/Image_Segmentation
but we have no papers on the combination of trans-unet with R2unet. this is my idea maybe I could improve trans-unet results, but I dont know how to implment it.

**Comment by yingkaisha** [comment]
The R2-Attention looks not so different from the R2-UNET that this repo has. I don't know if trans-unet can be improved in that way. Looking forward to your future work.
