### ISSUE TITLE
input output issue

### ISSUE THREAD

**Issue by soheilmajidi** [yingkaisha/keras-unet-collection#33]
Intro:
in image denoising encoder-decoder networks are perfect like auto-encoders and u-net networks have same property, but you design your network just for image segmentation.
issue:
for your network: input is RGB image and out put is binary mask, so that network will train and learn how to segment special part of image.
my error: I have noisy RGB image as input and RGB clean image as output(here as mask) so that my network k will learn how to clear noise from image.
my question: how can I change network in a way that accept both input and output in RGB (None,None,3)?

**Comment by yingkaisha** [comment]
Set the keyword `n_labels=3` should work in this case. Can you post your model configuration?

**Comment by soheilmajidi** [comment]
thanks.
it worked
