### ISSUE TITLE
how to use more than 3 channel input

### ISSUE THREAD

**Issue by rezadarooei** [yingkaisha/keras-unet-collection#35]
is it possible to use more than 3 channels as input? I want to concentrate on different images transforming and creating more than 3 channels. I used that method and put input_size=(512,512,4) but I got the error, is there any way I could use more than 3 channels?

![image](https://user-images.githubusercontent.com/33072741/142064102-14d49e11-5241-40d6-b1ce-5bf5f883a815.png)

**Comment by yingkaisha** [comment]
I will look into it around Friday.

**Comment by yingkaisha** [comment]
Hi, sorry for getting back to it late. I saw `cuDNN launch failure` in your error message. It is likely not related to the number of channels. 

Would you mind sharing your code blocks? In addition, perhaps you need to track your GPU memory usage and Tensorflow/CUDA versions.

**Comment by rezadarooei** [comment]
hello dear,
I found the best way to solve this problem for more than 3 channel is using dataset type. it solves my problem.
