### ISSUE TITLE
CGM模块训练

### ISSUE THREAD

**Issue by atgc1984** [yingkaisha/keras-unet-collection#6]
Hello，请问下UNET3+ example里CGM值应该如何训练？论文里好像也没见详细描述。是需要用数据集里的阴性样本去单独训练模型吗？谢谢。

**Comment by yingkaisha** [comment]
您好。我不知道，但是可参考 https://github.com/ZJUGiveLab/UNet-Version/blob/master/models/UNet_3Plus.py

**Comment by atgc1984** [comment]
好的，十分感谢！
